/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;
//import Class.Model_Hasilpanen;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import Class.koneksi;

/**
 *
 * @author asus
 */
public class hasil_Panen extends javax.swing.JPanel {
private void loadTable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Tanggal");
    model.addColumn("Nama Barang");
    model.addColumn("Total Panen (Kg)");
    model.addColumn("Pengeluaran");
    model.addColumn("Panen Bersih");

    try {
        Connection con = koneksi.configDB();
        String sql = "SELECT * FROM hasil_panen ORDER BY id_panen DESC";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getDate("tgl_panen"),
                rs.getString("nama_barang"),
                rs.getDouble("total_panen"),
                rs.getDouble("total_pengeluaran_barang"),
                rs.getDouble("panen_bersih")
            });
        }

        jTable.setModel(model);

    } catch (Exception e) {
        System.out.println("Error load table: " + e);
    }
}

    /**
     * Creates new form hasil_Panen
     */
    public hasil_Panen() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTotalPanen = new javax.swing.JTextField();
        Bsimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bKembali = new javax.swing.JButton();
        cmbBarang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(138, 195, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setBackground(new java.awt.Color(204, 255, 204));
        jTable.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 174, 962, 383));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel1.setText("Hasil Panen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 16, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 43, 962, -1));

        txtTotalPanen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPanenActionPerformed(evt);
            }
        });
        add(txtTotalPanen, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 111, 210, 30));

        Bsimpan.setBackground(new java.awt.Color(0, 153, 0));
        Bsimpan.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        Bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        Bsimpan.setText("Simpan");
        Bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsimpanActionPerformed(evt);
            }
        });
        add(Bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 32));

        bHapus.setBackground(new java.awt.Color(0, 153, 0));
        bHapus.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 32));

        bKembali.setBackground(new java.awt.Color(0, 153, 0));
        bKembali.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        bKembali.setForeground(new java.awt.Color(255, 255, 255));
        bKembali.setText("Kembali");
        add(bKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, 32));

        cmbBarang.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padi", "Jagung", "Bawang Merah", " " }));
        add(cmbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 73, 210, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        jLabel2.setText("Nama barang");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalPanenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPanenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPanenActionPerformed

    private void BsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsimpanActionPerformed
        // TODO add your handling code here:private void BsimpanActionPerformed(java.awt.event.ActionEvent evt) {
    //int idUser = UserSession.getIdUser(); // OTOMATIS
    String namaBarang = cmbBarang.getSelectedItem().toString();
    double totalPanen = Double.parseDouble(txtTotalPanen.getText());

    //Model_HasilPanen panen = new Model_HasilPanen();
    //panen.simpan(idUser, namaBarang, totalPanen);

    loadTable();
    JOptionPane.showMessageDialog(this, "Data panen berhasil disimpan");

    }//GEN-LAST:event_BsimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsimpan;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtTotalPanen;
    // End of variables declaration//GEN-END:variables
}
